hostname p1
log stdout
!
interface eth1
 ip address 10.1.1.2/24
 ip ospf area 0.0.0.0
exit
!
interface eth2
 ip address 10.2.2.2/24
 ip ospf area 0.0.0.0
exit
!
router ospf
 ospf router-id 1.1.1.1
exit
!